# Generated by Django 2.2.7 on 2020-03-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_touragents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='touragents',
            name='location',
            field=models.CharField(default='place', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carimagemodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa', to='users.Driver'),
        ),
    ]
