# Generated by Django 2.2.7 on 2020-03-09 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_touragents_first_to_ten_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='touragents',
            name='date_of_tour',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
