# Generated by Django 2.2.7 on 2020-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_touragents_date_of_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='touragents',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
