# Generated by Django 2.2.7 on 2020-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_touragents_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touragents',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
