# Generated by Django 2.2.7 on 2020-03-10 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200310_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(null=True, upload_to='img')),
                ('first_to_ten_price', models.IntegerField(default=0)),
                ('date_of_tour', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('quantity', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TourAgents')),
            ],
        ),
        migrations.DeleteModel(
            name='TourAgentsImageModel',
        ),
    ]
