# Generated by Django 2.2.7 on 2020-03-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200310_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='mainimage',
        ),
    ]
