# Generated by Django 2.2.7 on 2020-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_choices',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Client'), (3, 'Guide'), (4, 'TourAgents')], default=1),
        ),
    ]
