# Generated by Django 2.2.7 on 2020-03-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_user_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.IntegerField(choices=[(1, 'BMW'), (2, 'Mercedes Benz')]),
        ),
    ]
