# Generated by Django 2.2.7 on 2020-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_touragents_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(default='Tour_name', max_length=255),
            preserve_default=False,
        ),
    ]
