# Generated by Django 2.2.7 on 2020-04-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
            preserve_default=False,
        ),
    ]
