# Generated by Django 2.2.7 on 2020-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_guide_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='age',
            field=models.IntegerField(choices=[(1, '18-25'), (2, '25-35'), (2, '35+')], default=1),
            preserve_default=False,
        ),
    ]
