# Generated by Django 2.2.7 on 2020-04-02 09:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_guide_car_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
