# Generated by Django 2.2.7 on 2020-04-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_guide_my_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='my_field',
        ),
    ]
