# Generated by Django 2.2.7 on 2020-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200402_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='invalid_chairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='kid_seats',
            field=models.BooleanField(default=False),
        ),
    ]
