# Generated by Django 2.2.7 on 2020-04-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200403_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
