# Generated by Django 2.2.7 on 2020-04-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200403_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touragents',
            name='language',
        ),
    ]
