# Generated by Django 2.2.7 on 2020-04-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_touragents_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touragents',
            name='location',
        ),
    ]
