# Generated by Django 2.2.7 on 2020-04-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_touragents_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAgentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(blank=True, null=True, upload_to='img')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TourAgents')),
            ],
        ),
    ]
