# Generated by Django 2.2.7 on 2020-04-04 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200405_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='tour',
            name='rout',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
