# Generated by Django 2.2.7 on 2020-04-07 17:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200405_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='first_to_ten_price',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='location',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='location_based_price',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='ten_plus_one_price',
        ),
        migrations.AddField(
            model_name='guide',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='free_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Frayday'), (6, 'Saturday'), (7, 'Sunday')], default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='guide',
            name='region',
            field=models.IntegerField(choices=[(1, 'Armavir'), (2, 'Yerevan'), (3, 'Kotayq')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='tour_type',
            field=models.IntegerField(choices=[(1, 'Extreme')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guide',
            name='age',
            field=models.IntegerField(choices=[(1, '18-25'), (2, '25-35'), (3, '35+')]),
        ),
    ]
