# Generated by Django 2.2.7 on 2020-04-07 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200405_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
