# Generated by Django 2.2.7 on 2020-04-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200407_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='first_to_ten_price',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='location',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='location_based_price',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='ten_plus_one_price',
        ),
    ]
