# Generated by Django 2.2.7 on 2020-04-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200407_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.IntegerField(choices=[(1, 'BMW'), (2, 'Mercedes Benz')])),
                ('production_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], verbose_name='year')),
                ('seats', models.IntegerField()),
                ('kid_seats', models.BooleanField(default=False)),
                ('invalid_chairs', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='img')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='car_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Car'),
        ),
    ]
