# Generated by Django 2.2.7 on 2020-04-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20200407_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='car_info',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
