# Generated by Django 2.2.7 on 2020-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20200407_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='car',
            field=models.IntegerField(choices=[(1, 'BMW'), (2, 'Mercedes Benz')], null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='guide',
            name='invalid_chairs',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='kid_seats',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='production_year',
            field=models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], null=True, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='guide',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
