# Generated by Django 2.2.7 on 2020-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20200408_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='trip_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
