# Generated by Django 2.2.7 on 2020-04-08 21:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20200408_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Armenian'), (2, 'English'), (3, 'France'), (4, 'Russian')], max_length=7, null=True, verbose_name='language'),
        ),
    ]
